/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Connections
         * @description Every MCP server, its tools, access tier, and enterprise health — for the portal.
         */
        get: operations["connections_connections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Investigate
         * @description Run the Investigator: plan -> tool loop -> synthesized Finding, one trace id.
         */
        post: operations["post_investigate_investigate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Trades
         * @description Proxy to the enterprise trade search — the portal talks only to platform-api.
         */
        get: operations["list_trades_trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trades/{trade_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trade */
        get: operations["get_trade_trades__trade_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Knowledge
         * @description Search the SOP / fixture corpus — for the portal's Knowledge tab.
         */
        get: operations["knowledge_knowledge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConnectionsResponse */
        ConnectionsResponse: {
            /** Enterprise Base Url */
            enterprise_base_url: string;
            /** Healthy */
            healthy: boolean;
            /** Servers */
            servers: components["schemas"]["ServerInfo"][];
        };
        /** EvidenceRef */
        EvidenceRef: {
            /** Kind */
            kind: string;
            /** Ref */
            ref: string;
            /**
             * Cited
             * @default true
             */
            cited: boolean;
        };
        /** Finding */
        Finding: {
            subject: components["schemas"]["SubjectRef"];
            outcome: components["schemas"]["Outcome"];
            /** Root Cause */
            root_cause?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceRef"][];
            /** Proposed Actions */
            proposed_actions?: components["schemas"]["ProposedAction"][];
            /** Rejected Alternatives */
            rejected_alternatives?: components["schemas"]["RejectedAlternative"][];
            /** Open Questions */
            open_questions?: string[];
            /** Checked */
            checked?: string[];
            /** Degraded Tools */
            degraded_tools?: string[];
            /**
             * Confidence Basis
             * @default
             */
            confidence_basis: string;
            /**
             * Trace Id
             * @default
             */
            trace_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvestigateRequest */
        InvestigateRequest: {
            /** Trade Id */
            trade_id: string;
        };
        /** KnowledgeHit */
        KnowledgeHit: {
            /** Doc */
            doc: string;
            /**
             * Section
             * @default
             */
            section: string;
            /**
             * Title
             * @default
             */
            title: string;
            /** Text */
            text: string;
            /** Score */
            score: number;
        };
        /**
         * Outcome
         * @enum {string}
         */
        Outcome: "RESOLVED_CAUSE" | "INSUFFICIENT_EVIDENCE" | "TOOL_DEGRADED" | "OUT_OF_SCOPE" | "SKELETON";
        /** ProposedAction */
        ProposedAction: {
            /** Action Type */
            action_type: string;
            /** Params */
            params?: {
                [key: string]: string;
            };
            /** Rationale */
            rationale: string;
            /** Impact */
            impact?: components["schemas"]["SubjectRef"][];
            /**
             * Reversible
             * @default true
             */
            reversible: boolean;
        };
        /** RejectedAlternative */
        RejectedAlternative: {
            /** Action Type */
            action_type: string;
            /** Reason */
            reason: string;
            /** Evidence */
            evidence?: string[];
        };
        /** ServerInfo */
        ServerInfo: {
            /** Name */
            name: string;
            /** Access */
            access: string;
            /** Healthy */
            healthy: boolean;
            /** Tools */
            tools: components["schemas"]["ToolInfo"][];
        };
        /** SubjectRef */
        SubjectRef: {
            /** Type */
            type: string;
            /** Id */
            id: string;
        };
        /** ToolInfo */
        ToolInfo: {
            /** Name */
            name: string;
            /** Access */
            access: string;
            /** Description */
            description: string;
        };
        /** TradeRow */
        TradeRow: {
            /** Trade Id */
            trade_id: string;
            /** Client Id */
            client_id?: string | null;
            /** Account Id */
            account_id?: string | null;
            /** Security Id */
            security_id?: string | null;
            /** Qty */
            qty?: number | null;
            /** Side */
            side?: string | null;
            /** Price */
            price?: number | null;
            /** Trade Date */
            trade_date?: string | null;
            /** Settle Date */
            settle_date?: string | null;
            /** Status */
            status?: string | null;
            /** Cpty Id */
            cpty_id?: string | null;
            /** Booked At */
            booked_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    connections_connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionsResponse"];
                };
            };
        };
    };
    post_investigate_investigate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trades_trades_get: {
        parameters: {
            query?: {
                client?: string | null;
                account?: string | null;
                status?: string | null;
                security?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trade_trades__trade_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trade_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    knowledge_knowledge_get: {
        parameters: {
            query: {
                q: string;
                k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
