/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Traces */
        get: operations["list_traces_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traces/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diff Traces */
        get: operations["diff_traces_traces_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace */
        get: operations["get_trace_traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traces/{trace_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Trace */
        get: operations["export_trace_traces__trace_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traces/{trace_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replay Trace */
        post: operations["replay_trace_traces__trace_id__replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Connections
         * @description Every MCP server, its tools, access tier, and enterprise health — for the portal.
         */
        get: operations["connections_connections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Investigate
         * @description Investigate a trade (Settlement specialist) or a whole client (Supervisor fan-out).
         *
         *     `{"trade_id": ...}` runs the single-trade path; `{"client_id": ...}` decomposes across
         *     specialists, correlates, and returns one client-level Finding with `sub_findings`.
         */
        post: operations["post_investigate_investigate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Diagnose
         * @description Developer Agent — incident mode. Diagnose a platform fault (failing job / degraded
         *     service): find the causing change, the blast radius, and revert-vs-fix-forward, and
         *     propose a change ticket + rerun for a human to approve.
         */
        post: operations["post_diagnose_diagnose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Review Pr
         * @description Developer Agent — PR-review mode. Classify the touched surfaces, run the
         *     deterministic checks, apply the platform hard rules (write tool w/o approval_id →
         *     BLOCKER, new action not on an allowlist → MAJOR, PII into a model call → BLOCKER,
         *     agent-authored scenario → needs a human), and return a structured `Review`. It posts
         *     comments only — there is no approve/merge tool.
         */
        post: operations["post_review_pr_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Verify
         * @description Developer Agent — verification mode. Apply a change ticket, re-check the signals
         *     the diagnosis used, hand residual trades to Settlement, and write an incident on a
         *     clean fix. On failure it reports — it never proposes a second fix.
         */
        post: operations["post_verify_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Event
         * @description Publish an estate event onto the bus (demo / portal convenience — the simulator is
         *     the usual publisher). The in-process consumer picks it up and opens a case.
         */
        post: operations["publish_event_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Trades
         * @description Proxy to the enterprise trade search — the portal talks only to platform-api.
         */
        get: operations["list_trades_trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trades/{trade_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trade */
        get: operations["get_trade_trades__trade_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Knowledge
         * @description Search the SOP / fixture corpus — for the portal's Knowledge tab.
         */
        get: operations["knowledge_knowledge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cases
         * @description All cases, newest first — for the portal's Cases tab.
         */
        get: operations["list_cases_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{approval_id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Approval
         * @description A human (role `OPS_ANALYST`) approves or rejects a proposed action.
         */
        post: operations["decide_approval_approvals__approval_id__decide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConnectionsResponse */
        ConnectionsResponse: {
            /** Enterprise Base Url */
            enterprise_base_url: string;
            /** Healthy */
            healthy: boolean;
            /** Servers */
            servers: components["schemas"]["ServerInfo"][];
        };
        /** DecideRequest */
        DecideRequest: {
            /** Decision */
            decision: string;
            /** Decided By */
            decided_by: string;
            /**
             * Role
             * @default OPS_ANALYST
             */
            role: string;
        };
        /** DiagnoseRequest */
        DiagnoseRequest: {
            /** Subject Id */
            subject_id: string;
            /** Request */
            request?: string | null;
        };
        /**
         * Event
         * @description A thing that happened in the estate. `id` is set by the bus on publish.
         */
        Event: {
            /**
             * Id
             * @default
             */
            id: string;
            /**
             * Topic
             * @default settlement.events
             */
            topic: string;
            /** Type */
            type: string;
            /**
             * Subject Type
             * @default trade
             */
            subject_type: string;
            /** Subject Id */
            subject_id: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
        };
        /** EvidenceLink */
        EvidenceLink: {
            /** Ref */
            ref: string;
            /** Span Id */
            span_id: string;
        };
        /** EvidenceRef */
        EvidenceRef: {
            /** Kind */
            kind: string;
            /** Ref */
            ref: string;
            /**
             * Cited
             * @default true
             */
            cited: boolean;
        };
        /** Finding */
        Finding: {
            subject: components["schemas"]["SubjectRef"];
            outcome: components["schemas"]["Outcome"];
            /** Root Cause */
            root_cause?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceRef"][];
            /** Proposed Actions */
            proposed_actions?: components["schemas"]["ProposedAction"][];
            /** Rejected Alternatives */
            rejected_alternatives?: components["schemas"]["RejectedAlternative"][];
            /** Open Questions */
            open_questions?: string[];
            /** Checked */
            checked?: string[];
            /** Degraded Tools */
            degraded_tools?: string[];
            /**
             * Confidence Basis
             * @default
             */
            confidence_basis: string;
            /**
             * Trace Id
             * @default
             */
            trace_id: string;
            /**
             * Case Id
             * @default
             */
            case_id: string;
            /**
             * Planning Turns
             * @default 1
             */
            planning_turns: number;
            /** Sub Findings */
            sub_findings?: components["schemas"]["Finding"][];
            /** Blast Radius */
            blast_radius?: components["schemas"]["SubjectRef"][];
            /**
             * Fix Strategy
             * @default
             */
            fix_strategy: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvestigateRequest */
        InvestigateRequest: {
            /** Trade Id */
            trade_id?: string | null;
            /** Client Id */
            client_id?: string | null;
            /** Loan Id */
            loan_id?: string | null;
            /** Margin Call Id */
            margin_call_id?: string | null;
        };
        /** KnowledgeHit */
        KnowledgeHit: {
            /** Doc */
            doc: string;
            /**
             * Section
             * @default
             */
            section: string;
            /**
             * Title
             * @default
             */
            title: string;
            /** Text */
            text: string;
            /** Score */
            score: number;
        };
        /**
         * Outcome
         * @enum {string}
         */
        Outcome: "RESOLVED_CAUSE" | "INSUFFICIENT_EVIDENCE" | "TOOL_DEGRADED" | "OUT_OF_SCOPE" | "SKELETON";
        /** ProposedAction */
        ProposedAction: {
            /** Action Type */
            action_type: string;
            /** Params */
            params?: {
                [key: string]: string;
            };
            /** Rationale */
            rationale: string;
            /** Impact */
            impact?: components["schemas"]["SubjectRef"][];
            /**
             * Reversible
             * @default true
             */
            reversible: boolean;
            /** Approval Id */
            approval_id?: string | null;
            /**
             * Proposed By
             * @default
             */
            proposed_by: string;
        };
        /** RejectedAlternative */
        RejectedAlternative: {
            /** Action Type */
            action_type: string;
            /** Reason */
            reason: string;
            /** Evidence */
            evidence?: string[];
        };
        /** Review */
        Review: {
            /** Pr Id */
            pr_id: string;
            /** Surfaces */
            surfaces?: string[];
            /** Findings */
            findings?: components["schemas"]["ReviewFinding"][];
            /**
             * Recommendation
             * @default COMMENT
             */
            recommendation: string;
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /** ReviewFinding */
        ReviewFinding: {
            /** Severity */
            severity: string;
            /** File */
            file: string;
            /**
             * Line
             * @default 0
             */
            line: number;
            /** Message */
            message: string;
            /**
             * Evidence
             * @default
             */
            evidence: string;
            /**
             * Suggested Patch
             * @default
             */
            suggested_patch: string;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /** Pr Id */
            pr_id: string;
        };
        /** ServerInfo */
        ServerInfo: {
            /** Name */
            name: string;
            /** Access */
            access: string;
            /** Healthy */
            healthy: boolean;
            /** Tools */
            tools: components["schemas"]["ToolInfo"][];
        };
        /** SpanRow */
        SpanRow: {
            /** Span Id */
            span_id: string;
            /** Trace Id */
            trace_id: string;
            /**
             * Parent Span Id
             * @default
             */
            parent_span_id: string;
            /** Name */
            name: string;
            /**
             * Span Type
             * @default
             */
            span_type: string;
            /**
             * Agent
             * @default
             */
            agent: string;
            /**
             * Step
             * @default
             */
            step: string;
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /**
             * Status
             * @default
             */
            status: string;
            /**
             * Attributes
             * @default {}
             */
            attributes: {
                [key: string]: unknown;
            };
            /** Payload In */
            payload_in?: unknown;
            /** Payload Out */
            payload_out?: unknown;
        };
        /** SubjectRef */
        SubjectRef: {
            /** Type */
            type: string;
            /** Id */
            id: string;
        };
        /** ToolInfo */
        ToolInfo: {
            /** Name */
            name: string;
            /** Access */
            access: string;
            /** Description */
            description: string;
        };
        /** TraceDetail */
        TraceDetail: {
            /** Trace Id */
            trace_id: string;
            /**
             * Subject Type
             * @default
             */
            subject_type: string;
            /**
             * Subject Id
             * @default
             */
            subject_id: string;
            /**
             * Request
             * @default
             */
            request: string;
            /**
             * Scenario Id
             * @default
             */
            scenario_id: string;
            /**
             * Case Id
             * @default
             */
            case_id: string;
            /**
             * Agent
             * @default
             */
            agent: string;
            /**
             * Outcome
             * @default
             */
            outcome: string;
            /**
             * Root Cause
             * @default
             */
            root_cause: string;
            /**
             * Status
             * @default
             */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /**
             * Tool Calls
             * @default 0
             */
            tool_calls: number;
            /**
             * Retrievals
             * @default 0
             */
            retrievals: number;
            /**
             * Model Calls
             * @default 0
             */
            model_calls: number;
            /**
             * Tokens In
             * @default 0
             */
            tokens_in: number;
            /**
             * Tokens Out
             * @default 0
             */
            tokens_out: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /** Finding */
            finding?: {
                [key: string]: unknown;
            } | null;
            /**
             * Spans
             * @default []
             */
            spans: components["schemas"]["SpanRow"][];
            /**
             * Links
             * @default []
             */
            links: components["schemas"]["EvidenceLink"][];
        };
        /** TraceDiff */
        TraceDiff: {
            /** A */
            a: string;
            /** B */
            b: string;
            /** Same Scenario */
            same_scenario: boolean;
            /** Root Cause */
            root_cause: {
                [key: string]: string | null;
            };
            /** Outcome */
            outcome: {
                [key: string]: string | null;
            };
            /**
             * Tool Calls Added
             * @default []
             */
            tool_calls_added: string[];
            /**
             * Tool Calls Removed
             * @default []
             */
            tool_calls_removed: string[];
            /**
             * Tool Calls Reordered
             * @default false
             */
            tool_calls_reordered: boolean;
            /**
             * Retrieval Delta
             * @default []
             */
            retrieval_delta: {
                [key: string]: unknown;
            }[];
            /** Proposed Actions */
            proposed_actions: {
                [key: string]: string[];
            };
            /**
             * Tokens Delta
             * @default 0
             */
            tokens_delta: number;
            /**
             * Duration Ms Delta
             * @default 0
             */
            duration_ms_delta: number;
            /**
             * Cost Usd Delta
             * @default 0
             */
            cost_usd_delta: number;
        };
        /** TraceReplay */
        TraceReplay: {
            /** Original Trace Id */
            original_trace_id: string;
            /** Replay Trace Id */
            replay_trace_id: string;
            /** Original Finding */
            original_finding?: {
                [key: string]: unknown;
            } | null;
            /** Replay Finding */
            replay_finding?: {
                [key: string]: unknown;
            } | null;
        };
        /** TraceSummary */
        TraceSummary: {
            /** Trace Id */
            trace_id: string;
            /**
             * Subject Type
             * @default
             */
            subject_type: string;
            /**
             * Subject Id
             * @default
             */
            subject_id: string;
            /**
             * Request
             * @default
             */
            request: string;
            /**
             * Scenario Id
             * @default
             */
            scenario_id: string;
            /**
             * Case Id
             * @default
             */
            case_id: string;
            /**
             * Agent
             * @default
             */
            agent: string;
            /**
             * Outcome
             * @default
             */
            outcome: string;
            /**
             * Root Cause
             * @default
             */
            root_cause: string;
            /**
             * Status
             * @default
             */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /**
             * Tool Calls
             * @default 0
             */
            tool_calls: number;
            /**
             * Retrievals
             * @default 0
             */
            retrievals: number;
            /**
             * Model Calls
             * @default 0
             */
            model_calls: number;
            /**
             * Tokens In
             * @default 0
             */
            tokens_in: number;
            /**
             * Tokens Out
             * @default 0
             */
            tokens_out: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
        };
        /** TradeRow */
        TradeRow: {
            /** Trade Id */
            trade_id: string;
            /** Client Id */
            client_id?: string | null;
            /** Account Id */
            account_id?: string | null;
            /** Security Id */
            security_id?: string | null;
            /** Qty */
            qty?: number | null;
            /** Side */
            side?: string | null;
            /** Price */
            price?: number | null;
            /** Trade Date */
            trade_date?: string | null;
            /** Settle Date */
            settle_date?: string | null;
            /** Status */
            status?: string | null;
            /** Cpty Id */
            cpty_id?: string | null;
            /** Booked At */
            booked_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyRequest */
        VerifyRequest: {
            /** Ticket Id */
            ticket_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_traces_traces_get: {
        parameters: {
            query?: {
                case_id?: string | null;
                scenario_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_traces_traces_diff_get: {
        parameters: {
            query: {
                a: string;
                b: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceDiff"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_trace_traces__trace_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_trace_traces__trace_id__replay_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceReplay"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    connections_connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionsResponse"];
                };
            };
        };
    };
    post_investigate_investigate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_diagnose_diagnose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnoseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_review_pr_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_verify_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_event_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Event"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trades_trades_get: {
        parameters: {
            query?: {
                client?: string | null;
                account?: string | null;
                status?: string | null;
                security?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trade_trades__trade_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trade_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    knowledge_knowledge_get: {
        parameters: {
            query: {
                q: string;
                k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    get_case_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_approval_approvals__approval_id__decide_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
